# 1)Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [52]:
import numpy as np
import pandas as pd

In [53]:
def Alexandre_Théophile_Vandermond(input_vector, col, increasing=False):
    if increasing==False:
        
        mat = np.array([x**(col-i-1) for x in input_vector for i in range(col)]).reshape(len(input_vector),col)
    else:
        mat = np.array([x**i for x in input_vector for i in range(col)]).reshape(len(input_vector),col)
    return mat

In [54]:
input_vector = np.array([2,3,5,6])

In [55]:
output_matrix_decreasing = Alexandre_Théophile_Vandermond(input_vector=input_vector, col=4, increasing=False)

In [56]:
output_matrix_decreasing

array([[  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [216,  36,   6,   1]])

In [57]:
output_matrix_increasing = Alexandre_Théophile_Vandermond(input_vector=input_vector, col=4, increasing=True)

In [58]:
output_matrix_increasing

array([[  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125],
       [  1,   6,  36, 216]])

# 2 )Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [59]:
b = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [61]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Method 1

In [62]:
def Moving_sum(data, windowsSize):
    k=windowsSize
    seq = data
    moving_element = []
    
    for i in seq:
        moving_sum = 0
        moving_avg = 0
        indx = np.where(seq == i)
        if indx[0][0] >len(seq)-k:
            break
        else:
            n = indx[0][0]+k
            for j in range(indx[0][0],n):
                moving_sum = moving_sum+seq[j]
        moving_avg = round(moving_sum/k,2)
        moving_element.append(moving_avg)
    
    return(moving_element)

In [63]:
t = Moving_sum(b, 3)

In [64]:
t

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

# Method 2 Using Cumsum

In [67]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
